import { z } from 'zod';

export const ffDataSchema = z.object({
    analysis: z.array(
        z.object({
            explanation: z.string(),
            playerOneWeeks: z.number(),
            playerTwoWeeks: z.number(),
            playerOnePosition: z.string(),
            playerTwoPosition: z.string(),
            playerOneName: z.string(),
            playerTwoName: z.string(),

            // Historical data for player one
            playerOneStats: z.object({
                'nflverse_play_by_play_2023': z.object({
                    recYards: z.number(),
                    rushYards: z.number(),
                    touchdowns: z.number(),
                    receptions: z.number(),
                    airYards: z.number(),
                    yardsAfterCatch: z.number(),
                    yardsPerReception: z.number(),
                    passAttempt: z.number(),
                    passCompletion: z.number(),
                    interceptions: z.number(),
                    passYards: z.number(),
                    passTouchdowns: z.number(),
                }),
                'nflverse_play_by_play_2022': z.object({
                    recYards: z.number(),
                    rushYards: z.number(),
                    touchdowns: z.number(),
                    receptions: z.number(),
                    airYards: z.number(),
                    yardsAfterCatch: z.number(),
                    yardsPerReception: z.number(),
                    passAttempt: z.number(),
                    passCompletion: z.number(),
                    interceptions: z.number(),
                    passYards: z.number(),
                    passTouchdowns: z.number(),
                }),
                'nflverse_play_by_play_2021': z.object({
                    recYards: z.number(),
                    rushYards: z.number(),
                    touchdowns: z.number(),
                    receptions: z.number(),
                    airYards: z.number(),
                    yardsAfterCatch: z.number(),
                    yardsPerReception: z.number(),
                    passAttempt: z.number(),
                    passCompletion: z.number(),
                    interceptions: z.number(),
                    passYards: z.number(),
                    passTouchdowns: z.number(),
                }),
            }),

            // Historical data for player two
            playerTwoStats: z.object({
                'nflverse_play_by_play_2023': z.object({
                    recYards: z.number(),
                    rushYards: z.number(),
                    touchdowns: z.number(),
                    receptions: z.number(),
                    airYards: z.number(),
                    yardsAfterCatch: z.number(),
                    yardsPerReception: z.number(),
                    passAttempt: z.number(),
                    passCompletion: z.number(),
                    interceptions: z.number(),
                    passYards: z.number(),
                    passTouchdowns: z.number(),
                }),
                'nflverse_play_by_play_2022': z.object({
                    recYards: z.number(),
                    rushYards: z.number(),
                    touchdowns: z.number(),
                    receptions: z.number(),
                    airYards: z.number(),
                    yardsAfterCatch: z.number(),
                    yardsPerReception: z.number(),
                    passAttempt: z.number(),
                    passCompletion: z.number(),
                    interceptions: z.number(),
                    passYards: z.number(),
                    passTouchdowns: z.number(),
                }),
                'nflverse_play_by_play_2021': z.object({
                    recYards: z.number(),
                    rushYards: z.number(),
                    touchdowns: z.number(),
                    receptions: z.number(),
                    airYards: z.number(),
                    yardsAfterCatch: z.number(),
                    yardsPerReception: z.number(),
                    passAttempt: z.number(),
                    passCompletion: z.number(),
                    interceptions: z.number(),
                    passYards: z.number(),
                    passTouchdowns: z.number(),
                }),
            }),

            longestPlayOne: z.number(),
            longestPlayTwo: z.number(),
            safe_pick: z.string(),
            risky_pick: z.string(),
            recommended_pick: z.string().optional(),
            certainty: z.number().optional(),
            undecided: z.string().optional(),
        }),
    ),
});