import { z } from 'zod';

// define a schema for the notifications
export const ffDataSchema = z.object({
    analysis: z.array(
        z.object({
            explanation: z.string(),
            playerOneWeeks: z.number(),
            playerTwoWeeks: z.number(),
            playerOnePosition: z.string(),
            playerTwoPosition: z.string(),
            playerOneRecYards: z.number(),
            playerTwoRecYards: z.number(),
            playerOneRushYards: z.number(),
            playerTwoRushYards: z.number(),
            playerOneTouchdowns: z.number(),
            playerTwoTouchdowns: z.number(),
            playerOneReceptions: z.number(),
            playerTwoReceptions: z.number(),
            playerOneAirYards: z.number(),
            playerTwoAirYards: z.number(),
            playerOneYardsAfterCatch: z.number(),
            playerTwoYardsAfterCatch: z.number(),
            playerOneYardsPerReception: z.number(),
            playerTwoYardsPerReception: z.number(),
            playerOnePassAttempt: z.number(),
            playerTwoPassAttempt: z.number(),
            playerOnePassCompletion: z.number(),
            playerTwoPassCompletion: z.number(),
            playerOneInterceptions: z.number(),
            playerTwoInterceptions: z.number(),
            playerOnePassYards: z.number(),
            playerTwoPassYards: z.number(),
            playerOnePassTouchdowns: z.number(),
            playerTwoPassTouchdowns: z.number(),
            longestPlayOne: z.number(),
            longestPlayTwo: z.number(),
            safe_pick: z.string(),
            risky_pick: z.string(),
            recommended_pick: z.string().optional(),
            certainty: z.number().optional(),
            undecided: z.string().optional(),
        }),
    ),
});